name: Build Signed Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools python3-wheel unzip zip git wget
          pip3 install buildozer cython

      - name: Install Android SDK + Build Tools
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          unzip cmdtools.zip -d cmdline-tools
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Build unsigned release APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH
          buildozer -v android release

      - name: Sign APK
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > mykey.keystore
          UNSIGNED_APK=$(ls bin/*-release-unsigned.apk | head -n 1)
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore mykey.keystore \
            -storepass "$KEYSTORE_PASSWORD" \
            -keypass "$KEY_PASSWORD" \
            "$UNSIGNED_APK" "$KEY_ALIAS"

      - name: Align APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH
          UNSIGNED_APK=$(ls bin/*-release-unsigned.apk | head -n 1)
          zipalign -v -p 4 "$UNSIGNED_APK" bin/app-release-signed.apk

      - name: Verify APK Signature
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/build-tools/34.0.0:$PATH
          apksigner verify bin/app-release-signed.apk || true

      - name: Upload Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: bin/app-release-signed.apk
