name: Build Kivy APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90  # Increased timeout

    steps:
      - uses: actions/checkout@v4

      # Install system packages
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            unzip \
            wget \
            openjdk-17-jdk \
            python3-pip \
            git \
            rsync \
            autoconf \
            automake \
            libtool \
            pkg-config \
            build-essential \
            cmake \
            zlib1g-dev \
            libffi-dev \
            libssl-dev

      # Set Java 17 as default (updated from Java 8)
      - name: Set Java 17
        run: |
          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-17-openjdk-amd64/bin/java 1
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      # Install Android SDK Command Line Tools
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          unzip cmdtools.zip -d cmdline-tools
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/build-tools/33.0.2" >> $GITHUB_PATH

      # Install SDK packages (updated versions)
      - name: Install SDK packages
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2" \
            "platforms;android-21" \
            "build-tools;30.0.3"
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=$HOME/android-sdk

          # Symlink SDK into Buildozer's expected path
          mkdir -p $HOME/.buildozer/android/platform
          rm -rf $HOME/.buildozer/android/platform/android-sdk
          ln -s $HOME/android-sdk $HOME/.buildozer/android/platform/android-sdk

          # Create tools/bin directory for compatibility
          mkdir -p $HOME/.buildozer/android/platform/android-sdk/tools/bin
          ln -sf $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager $HOME/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install buildozer cython==0.29.33

      # Clean previous builds
      - name: Clean previous builds
        run: |
          rm -rf .buildozer
          rm -rf bin

      # Build debug APK first (easier to debug)
      - name: Build debug APK
        run: |
          export ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk
          export ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$ANDROIDSDK/platform-tools:$ANDROIDSDK/build-tools/33.0.2:$PATH
          
          # Build debug APK
          buildozer -v android debug

      # Generate keystore and build release APK (if debug succeeds)
      - name: Build release APK
        run: |
          export ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk
          export ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$ANDROIDSDK/platform-tools:$ANDROIDSDK/build-tools/33.0.2:$PATH
          
          # Clean and create keystore directory
          rm -rf keystore
          mkdir -p keystore
          
          # Generate keystore automatically
          keytool -genkey -v -keystore keystore/mykey.keystore -alias myalias -keyalg RSA -keysize 2048 -validity 10000 -storepass malikharisahmad -keypass malikharisahmad -dname "CN=York Hit, OU=Cricket, O=YorkHit, L=Lahore, S=Punjab, C=PK"
          
          # Build release APK
          buildozer -v android release

      # Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()  # Upload even if some steps fail
        with:
          name: york-hit-apk
          path: |
            bin/*.apk
            .buildozer/android/platform/build-*/dists/yorkhit*/build/outputs/apk/**/*.apk
          retention-days: 30

      # Upload build logs for debugging
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-logs
          path: |
            .buildozer/android/platform/build-*/logs/
            .buildozer/android/platform/logcat.txt
          retention-days: 7