name: Build Kivy APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install dependencies
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip wget openjdk-17-jdk python3-pip git

      # Install Android SDK Command Line Tools
      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdtools.zip
          unzip cmdtools.zip -d cmdline-tools
          mkdir -p cmdline-tools/latest
          mv cmdline-tools/cmdline-tools/* cmdline-tools/latest/
          echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b" >> $GITHUB_ENV
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/build-tools/34.0.0" >> $GITHUB_PATH
          echo "$HOME/android-sdk/build-tools/33.0.2" >> $GITHUB_PATH

      # Install SDK packages (Android 34 + 33)
      - name: Install SDK packages
        run: |
          yes | sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "platforms;android-33" \
            "build-tools;33.0.2"
          yes | sdkmanager --licenses --sdk_root=$HOME/android-sdk

          # Copy SDK into the path Buildozer expects
          mkdir -p $HOME/.buildozer/android/platform
          rsync -a $HOME/android-sdk $HOME/.buildozer/android/platform/android-sdk

      # Install buildozer
      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      # Build unsigned APK (force SDK + NDK paths)
      - name: Build APK
        run: |
          export ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk
          export ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b
          export PATH=$ANDROIDSDK/platform-tools:$ANDROIDSDK/build-tools/34.0.0:$ANDROIDSDK/build-tools/33.0.2:$PATH
          buildozer -v android release

      # Sign the APK
      - name: Sign APK
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > mykey.keystore
          cp bin/*-release.apk app-release-unsigned.apk
          apksigner sign --ks mykey.keystore \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --out app-release.apk \
            app-release-unsigned.apk

      # Upload artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: signed-apk
          path: app-release.apk
